# Fabric notebook source
# ==========================================================================
# ZONE SCAFFOLD : SalesLakehouse
# AUTO-GENERATED by the Medallion Architecture Blueprint. Do not hand-edit.
# ==========================================================================

LAKEHOUSE = "SalesLakehouse"

# ---- Zone schemas (one per managed layer) --------------------------------
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {LAKEHOUSE}_bronze")
print(f"[ZONE] schema {LAKEHOUSE}_bronze ready  # Raw data landed as Delta, schema enforced, history preserved.")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {LAKEHOUSE}_silver")
print(f"[ZONE] schema {LAKEHOUSE}_silver ready  # Cleansed, de-duplicated, conformed business entities.")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {LAKEHOUSE}_gold")
print(f"[ZONE] schema {LAKEHOUSE}_gold ready  # Aggregated, business-ready marts for reporting.")

# ---- Landing folders (raw drop zone) -------------------------------------
mssparkutils.fs.mkdirs("Files/landing/sales/customer/")
print(f"[ZONE] landing path ready: Files/landing/sales/customer/")
mssparkutils.fs.mkdirs("Files/landing/sales/order/")
print(f"[ZONE] landing path ready: Files/landing/sales/order/")
mssparkutils.fs.mkdirs("Files/landing/sales/product/")
print(f"[ZONE] landing path ready: Files/landing/sales/product/")

print("[ZONE] Scaffold complete.")
