# Fabric notebook source
# ==========================================================================
# CREATE TABLE : order  (bronze layer)
# Target       : SalesLakehouse_bronze.bronze_order
# AUTO-GENERATED by the Medallion Architecture Blueprint. Do not hand-edit.
# ==========================================================================

from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType, LongType, ShortType,
    DoubleType, FloatType, DecimalType, BooleanType, DateType, TimestampType,
    BinaryType,
)
from delta.tables import DeltaTable

SCHEMA = "SalesLakehouse_bronze"
TABLE = "bronze_order"
FQN = f"{SCHEMA}.{TABLE}"

builder = (
    DeltaTable.createIfNotExists(spark)
    .tableName(FQN)
    # ---- Business columns (from manifest) --------------------------------
    .addColumn("order_id", LongType(), nullable=False)
    .addColumn("customer_id", LongType(), nullable=True)
    .addColumn("order_date", DateType(), nullable=True)
    .addColumn("amount", DecimalType(18,2), nullable=True)
    .addColumn("status", StringType(), nullable=True)
    # ---- Mandatory audit columns (bronze layer) ----------------
    .addColumn("_ingested_at", TimestampType())
    .addColumn("_source_system", StringType())
    .addColumn("_batch_id", StringType())
)
builder = builder.partitionedBy(["order_date"])
builder.execute()

# ---- Apply standard table properties -------------------------------------
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.autoOptimize.optimizeWrite' = 'true')")
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.autoOptimize.autoCompact' = 'true')")
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.minReaderVersion' = '2')")
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.minWriterVersion' = '5')")

print(f"[TABLE] {FQN} created/verified with "
      f"5 business + 3 audit columns.")
