# Fabric notebook source
# ==========================================================================
# CREATE TABLE : customer  (silver layer)
# Target       : SalesLakehouse_silver.silver_customer
# AUTO-GENERATED by the Medallion Architecture Blueprint. Do not hand-edit.
# ==========================================================================

from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType, LongType, ShortType,
    DoubleType, FloatType, DecimalType, BooleanType, DateType, TimestampType,
    BinaryType,
)
from delta.tables import DeltaTable

SCHEMA = "SalesLakehouse_silver"
TABLE = "silver_customer"
FQN = f"{SCHEMA}.{TABLE}"

builder = (
    DeltaTable.createIfNotExists(spark)
    .tableName(FQN)
    # ---- Business columns (from manifest) --------------------------------
    .addColumn("customer_id", LongType(), nullable=False)
    .addColumn("full_name", StringType(), nullable=True)
    .addColumn("email", StringType(), nullable=True)
    .addColumn("country", StringType(), nullable=True)
    # ---- Mandatory audit columns (silver layer) ----------------
    .addColumn("_updated_at", TimestampType())
)
builder = builder.partitionedBy(["country"])
builder.execute()

# ---- Apply standard table properties -------------------------------------
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.autoOptimize.optimizeWrite' = 'true')")
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.autoOptimize.autoCompact' = 'true')")
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.minReaderVersion' = '2')")
spark.sql(f"ALTER TABLE {FQN} SET TBLPROPERTIES ('delta.minWriterVersion' = '5')")

print(f"[TABLE] {FQN} created/verified with "
      f"4 business + 1 audit columns.")
